# Generated by Django 5.1.14 on 2026-03-17 08:34

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lims', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetadataFieldDefinition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('code', models.SlugField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, default='')),
                ('field_type', models.CharField(choices=[('text', 'Text'), ('long_text', 'Long Text'), ('integer', 'Integer'), ('decimal', 'Decimal'), ('boolean', 'Boolean'), ('date', 'Date'), ('datetime', 'Datetime'), ('choice', 'Choice'), ('multi_choice', 'Multi Choice')], max_length=32)),
                ('help_text', models.CharField(blank=True, default='', max_length=255)),
                ('placeholder', models.CharField(blank=True, default='', max_length=255)),
                ('default_value', models.JSONField(blank=True, null=True)),
                ('config', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MetadataSchema',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('code', models.SlugField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['code'], name='lims_meta_schema_code_idx')],
            },
        ),
        migrations.CreateModel(
            name='MetadataSchemaVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version_number', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('deprecated', 'Deprecated')], default='draft', max_length=16)),
                ('change_summary', models.CharField(blank=True, default='', max_length=255)),
                ('schema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='lims.metadataschema')),
            ],
            options={
                'ordering': ['schema__name', '-version_number'],
            },
        ),
        migrations.CreateModel(
            name='MetadataSchemaField',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('field_key', models.SlugField(max_length=100)),
                ('position', models.PositiveIntegerField(default=0)),
                ('required', models.BooleanField(default=False)),
                ('validation_rules', models.JSONField(blank=True, default=dict)),
                ('condition', models.JSONField(blank=True, default=dict)),
                ('field_definition', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='schema_fields', to='lims.metadatafielddefinition')),
                ('schema_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='lims.metadataschemaversion')),
            ],
            options={
                'ordering': ['schema_version__schema__name', 'schema_version__version_number', 'position', 'field_key'],
            },
        ),
        migrations.CreateModel(
            name='MetadataSchemaBinding',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('target_type', models.CharField(choices=[('sample_type', 'Sample Type'), ('workflow_step', 'Workflow Step')], max_length=32)),
                ('target_key', models.SlugField(max_length=100)),
                ('target_label', models.CharField(blank=True, default='', max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('schema_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bindings', to='lims.metadataschemaversion')),
            ],
            options={
                'ordering': ['target_type', 'target_key'],
            },
        ),
        migrations.CreateModel(
            name='MetadataVocabulary',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('code', models.SlugField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['code'], name='lims_meta_vocab_code_idx')],
            },
        ),
        migrations.AddField(
            model_name='metadatafielddefinition',
            name='vocabulary',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='field_definitions', to='lims.metadatavocabulary'),
        ),
        migrations.CreateModel(
            name='MetadataVocabularyItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('value', models.CharField(max_length=100)),
                ('label', models.CharField(max_length=200)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('vocabulary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='lims.metadatavocabulary')),
            ],
            options={
                'ordering': ['vocabulary__name', 'sort_order', 'label'],
            },
        ),
        migrations.AddConstraint(
            model_name='metadataschemaversion',
            constraint=models.UniqueConstraint(fields=('schema', 'version_number'), name='uniq_lims_meta_schema_version_number'),
        ),
        migrations.AddConstraint(
            model_name='metadataschemafield',
            constraint=models.UniqueConstraint(fields=('schema_version', 'field_key'), name='uniq_lims_meta_schema_field_key'),
        ),
        migrations.AddIndex(
            model_name='metadataschemabinding',
            index=models.Index(fields=['target_type', 'target_key'], name='lims_meta_binding_target_idx'),
        ),
        migrations.AddConstraint(
            model_name='metadataschemabinding',
            constraint=models.UniqueConstraint(fields=('target_type', 'target_key'), name='uniq_lims_meta_schema_binding_target'),
        ),
        migrations.AddIndex(
            model_name='metadatafielddefinition',
            index=models.Index(fields=['code'], name='lims_meta_field_code_idx'),
        ),
        migrations.AddConstraint(
            model_name='metadatavocabularyitem',
            constraint=models.UniqueConstraint(fields=('vocabulary', 'value'), name='uniq_lims_meta_vocab_item_value'),
        ),
    ]
