# Generated by hand for the biospecimen aggregate slice.

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lims", "0002_metadatafielddefinition_metadataschema_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="BiospecimenType",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=200)),
                ("key", models.SlugField(max_length=100, unique=True)),
                ("description", models.TextField(blank=True, default="")),
                ("identifier_prefix", models.CharField(default="SPEC", max_length=32)),
                ("barcode_prefix", models.CharField(default="BC", max_length=32)),
                ("sequence_padding", models.PositiveIntegerField(default=6)),
                ("next_sequence", models.PositiveIntegerField(default=1)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["name"],
                "indexes": [models.Index(fields=["key"], name="lims_bios_type_key_idx")],
            },
        ),
        migrations.CreateModel(
            name="Biospecimen",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("sample_identifier", models.CharField(max_length=64, unique=True)),
                ("barcode", models.CharField(max_length=64, unique=True)),
                ("kind", models.CharField(choices=[("primary", "Primary"), ("aliquot", "Aliquot")], default="primary", max_length=16)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("registered", "Registered"),
                            ("received", "Received"),
                            ("available", "Available"),
                            ("aliquoted", "Aliquoted"),
                            ("pooled", "Pooled"),
                            ("consumed", "Consumed"),
                            ("archived", "Archived"),
                            ("disposed", "Disposed"),
                        ],
                        default="registered",
                        max_length=16,
                    ),
                ),
                ("subject_identifier", models.CharField(blank=True, default="", max_length=100)),
                ("external_identifier", models.CharField(blank=True, default="", max_length=100)),
                ("quantity", models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ("quantity_unit", models.CharField(blank=True, default="mL", max_length=32)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("collected_at", models.DateTimeField(blank=True, null=True)),
                ("received_at", models.DateTimeField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "lab",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="biospecimens",
                        to="lims.lab",
                    ),
                ),
                (
                    "lineage_root",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="lineage_descendants",
                        to="lims.biospecimen",
                    ),
                ),
                (
                    "parent_specimen",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="aliquots",
                        to="lims.biospecimen",
                    ),
                ),
                (
                    "sample_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="biospecimens",
                        to="lims.biospecimentype",
                    ),
                ),
                (
                    "site",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="biospecimens",
                        to="lims.site",
                    ),
                ),
                (
                    "study",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="biospecimens",
                        to="lims.study",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["sample_identifier"], name="lims_bio_sample_id_idx"),
                    models.Index(fields=["barcode"], name="lims_bio_barcode_idx"),
                    models.Index(fields=["status", "-created_at"], name="lims_bio_status_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="BiospecimenPool",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("pool_identifier", models.CharField(max_length=64, unique=True)),
                ("barcode", models.CharField(max_length=64, unique=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("assembled", "Assembled"), ("consumed", "Consumed"), ("archived", "Archived")],
                        default="assembled",
                        max_length=16,
                    ),
                ),
                ("quantity", models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ("quantity_unit", models.CharField(blank=True, default="mL", max_length=32)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "lab",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="biospecimen_pools",
                        to="lims.lab",
                    ),
                ),
                (
                    "sample_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="pools",
                        to="lims.biospecimentype",
                    ),
                ),
                (
                    "site",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="biospecimen_pools",
                        to="lims.site",
                    ),
                ),
                (
                    "study",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="biospecimen_pools",
                        to="lims.study",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["pool_identifier"], name="lims_bio_pool_id_idx"),
                    models.Index(fields=["status", "-created_at"], name="lims_bio_pool_status_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="BiospecimenPoolMember",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("contributed_quantity", models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ("contributed_unit", models.CharField(blank=True, default="mL", max_length=32)),
                (
                    "pool",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="members",
                        to="lims.biospecimenpool",
                    ),
                ),
                (
                    "specimen",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="pool_memberships",
                        to="lims.biospecimen",
                    ),
                ),
            ],
            options={
                "ordering": ["pool__pool_identifier", "specimen__sample_identifier"],
            },
        ),
        migrations.AddConstraint(
            model_name="biospecimenpoolmember",
            constraint=models.UniqueConstraint(fields=("pool", "specimen"), name="uniq_lims_bio_pool_member"),
        ),
    ]
