# Generated by hand for the accessioning and receiving workflow slice.

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lims", "0003_biospecimens"),
    ]

    operations = [
        migrations.CreateModel(
            name="AccessioningManifest",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("manifest_identifier", models.CharField(max_length=64, unique=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("draft", "Draft"), ("submitted", "Submitted"), ("receiving", "Receiving"), ("received", "Received")],
                        default="draft",
                        max_length=16,
                    ),
                ),
                ("source_system", models.CharField(blank=True, default="", max_length=100)),
                ("source_reference", models.CharField(blank=True, default="", max_length=100)),
                ("notes", models.TextField(blank=True, default="")),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_by", models.CharField(blank=True, default="", max_length=100)),
                ("received_at", models.DateTimeField(blank=True, null=True)),
                (
                    "lab",
                    models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="accessioning_manifests", to="lims.lab"),
                ),
                (
                    "sample_type",
                    models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="accessioning_manifests", to="lims.biospecimentype"),
                ),
                (
                    "site",
                    models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="accessioning_manifests", to="lims.site"),
                ),
                (
                    "study",
                    models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="accessioning_manifests", to="lims.study"),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["manifest_identifier"], name="lims_acc_manifest_id_idx"),
                    models.Index(fields=["status", "-created_at"], name="lims_acc_manifest_status_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="AccessioningManifestItem",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("position", models.PositiveIntegerField(default=1)),
                ("expected_subject_identifier", models.CharField(blank=True, default="", max_length=100)),
                ("expected_sample_identifier", models.CharField(blank=True, default="", max_length=64)),
                ("expected_barcode", models.CharField(blank=True, default="", max_length=64)),
                ("quantity", models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ("quantity_unit", models.CharField(blank=True, default="mL", max_length=32)),
                ("collection_status", models.CharField(blank=True, default="", max_length=32)),
                ("notes", models.TextField(blank=True, default="")),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("status", models.CharField(choices=[("pending", "Pending"), ("received", "Received"), ("discrepant", "Discrepant")], default="pending", max_length=16)),
                ("received_at", models.DateTimeField(blank=True, null=True)),
                (
                    "biospecimen",
                    models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="manifest_items", to="lims.biospecimen"),
                ),
                (
                    "manifest",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="items", to="lims.accessioningmanifest"),
                ),
            ],
            options={
                "ordering": ["manifest__manifest_identifier", "position", "created_at"],
                "indexes": [models.Index(fields=["manifest", "status"], name="lims_acc_item_status_idx")],
            },
        ),
        migrations.CreateModel(
            name="ReceivingDiscrepancy",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("code", models.CharField(choices=[("barcode_mismatch", "Barcode Mismatch"), ("identifier_mismatch", "Identifier Mismatch"), ("missing_sample", "Missing Sample"), ("damaged_sample", "Damaged Sample"), ("metadata_mismatch", "Metadata Mismatch"), ("other", "Other")], max_length=32)),
                ("status", models.CharField(choices=[("open", "Open"), ("resolved", "Resolved")], default="open", max_length=16)),
                ("notes", models.TextField(blank=True, default="")),
                ("expected_data", models.JSONField(blank=True, default=dict)),
                ("actual_data", models.JSONField(blank=True, default=dict)),
                ("recorded_by", models.CharField(blank=True, default="", max_length=100)),
                (
                    "biospecimen",
                    models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="receiving_discrepancies", to="lims.biospecimen"),
                ),
                (
                    "manifest",
                    models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="discrepancies", to="lims.accessioningmanifest"),
                ),
                (
                    "manifest_item",
                    models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="discrepancies", to="lims.accessioningmanifestitem"),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [models.Index(fields=["status", "-created_at"], name="lims_receiving_disc_status_idx")],
            },
        ),
        migrations.CreateModel(
            name="ReceivingEvent",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("kind", models.CharField(choices=[("single", "Single"), ("manifest_item", "Manifest Item")], default="single", max_length=16)),
                ("received_by", models.CharField(blank=True, default="", max_length=100)),
                ("scan_value", models.CharField(blank=True, default="", max_length=100)),
                ("notes", models.TextField(blank=True, default="")),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("received_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "biospecimen",
                    models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="receiving_events", to="lims.biospecimen"),
                ),
                (
                    "manifest",
                    models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="receiving_events", to="lims.accessioningmanifest"),
                ),
                (
                    "manifest_item",
                    models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="receiving_events", to="lims.accessioningmanifestitem"),
                ),
            ],
            options={
                "ordering": ["-received_at", "-created_at"],
                "indexes": [models.Index(fields=["received_at"], name="lims_recv_evt_recv_idx")],
            },
        ),
        migrations.AddConstraint(
            model_name="accessioningmanifestitem",
            constraint=models.UniqueConstraint(fields=("manifest", "position"), name="uniq_lims_acc_manifest_item_position"),
        ),
    ]
