# Generated by hand to generalize geography for multi-country support.

import django.db.models.deletion
import uuid
from django.db import migrations, models


def forwards_generalize_geography(apps, schema_editor):
    Country = apps.get_model("lims", "Country")
    Region = apps.get_model("lims", "Region")
    District = apps.get_model("lims", "District")
    Ward = apps.get_model("lims", "Ward")
    Street = apps.get_model("lims", "Street")
    Postcode = apps.get_model("lims", "Postcode")
    TanzaniaRegion = apps.get_model("lims", "TanzaniaRegion")
    TanzaniaDistrict = apps.get_model("lims", "TanzaniaDistrict")
    TanzaniaWard = apps.get_model("lims", "TanzaniaWard")
    TanzaniaStreet = apps.get_model("lims", "TanzaniaStreet")
    Lab = apps.get_model("lims", "Lab")
    Site = apps.get_model("lims", "Site")

    country, _ = Country.objects.get_or_create(
        code="TZ",
        defaults={
            "name": "Tanzania",
            "slug": "tanzania",
            "source_url": "https://www.tanzaniapostcode.com/",
            "is_active": True,
        },
    )

    for old in TanzaniaRegion.objects.all():
        Region.objects.update_or_create(
            id=old.id,
            defaults={
                "country_id": country.id,
                "name": old.name,
                "slug": old.slug,
                "source_path": old.source_path,
                "source_url": old.source_url,
                "is_active": old.is_active,
                "last_synced_at": old.last_synced_at,
                "created_at": old.created_at,
                "updated_at": old.updated_at,
            },
        )

    for old in TanzaniaDistrict.objects.all():
        District.objects.update_or_create(
            id=old.id,
            defaults={
                "region_id": old.region_id,
                "name": old.name,
                "slug": old.slug,
                "source_path": old.source_path,
                "source_url": old.source_url,
                "is_active": old.is_active,
                "last_synced_at": old.last_synced_at,
                "created_at": old.created_at,
                "updated_at": old.updated_at,
            },
        )

    for old in TanzaniaWard.objects.all():
        Ward.objects.update_or_create(
            id=old.id,
            defaults={
                "district_id": old.district_id,
                "name": old.name,
                "slug": old.slug,
                "source_path": old.source_path,
                "source_url": old.source_url,
                "is_active": old.is_active,
                "last_synced_at": old.last_synced_at,
                "created_at": old.created_at,
                "updated_at": old.updated_at,
            },
        )

    for old in TanzaniaStreet.objects.all():
        Street.objects.update_or_create(
            id=old.id,
            defaults={
                "ward_id": old.ward_id,
                "name": old.name,
                "slug": old.slug,
                "source_path": old.source_path,
                "source_url": old.source_url,
                "is_active": old.is_active,
                "last_synced_at": old.last_synced_at,
                "created_at": old.created_at,
                "updated_at": old.updated_at,
            },
        )
        if old.postcode:
            Postcode.objects.update_or_create(
                source_path=old.source_path,
                defaults={
                    "street_id": old.id,
                    "code": old.postcode,
                    "source_url": old.source_url,
                    "is_active": old.is_active,
                    "last_synced_at": old.last_synced_at,
                },
            )

    Lab.objects.exclude(region_id=None).update(country_id=country.id)
    Lab.objects.filter(region_id=None).exclude(district_id=None).update(country_id=country.id)
    Lab.objects.filter(region_id=None, district_id=None).exclude(ward_id=None).update(country_id=country.id)
    Lab.objects.filter(region_id=None, district_id=None, ward_id=None).exclude(street_id=None).update(country_id=country.id)

    Site.objects.exclude(region_id=None).update(country_id=country.id)
    Site.objects.filter(region_id=None).exclude(district_id=None).update(country_id=country.id)
    Site.objects.filter(region_id=None, district_id=None).exclude(ward_id=None).update(country_id=country.id)
    Site.objects.filter(region_id=None, district_id=None, ward_id=None).exclude(street_id=None).update(country_id=country.id)


class Migration(migrations.Migration):

    dependencies = [
        ("lims", "0004_accessioning_workflows"),
    ]

    operations = [
        migrations.CreateModel(
            name="Country",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=200, unique=True)),
                ("code", models.CharField(max_length=8, unique=True)),
                ("slug", models.SlugField(blank=True, default="", max_length=220)),
                ("source_url", models.URLField(blank=True, default="", max_length=800)),
                ("is_active", models.BooleanField(default=True)),
                ("last_synced_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={"ordering": ["name"]},
        ),
        migrations.CreateModel(
            name="Region",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=200)),
                ("slug", models.SlugField(blank=True, default="", max_length=220)),
                ("source_path", models.CharField(max_length=500, unique=True)),
                ("source_url", models.URLField(max_length=800)),
                ("is_active", models.BooleanField(default=True)),
                ("last_synced_at", models.DateTimeField(blank=True, null=True)),
                ("country", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="regions", to="lims.country")),
            ],
            options={"ordering": ["country__name", "name"]},
        ),
        migrations.CreateModel(
            name="District",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=200)),
                ("slug", models.SlugField(blank=True, default="", max_length=220)),
                ("source_path", models.CharField(max_length=500, unique=True)),
                ("source_url", models.URLField(max_length=800)),
                ("is_active", models.BooleanField(default=True)),
                ("last_synced_at", models.DateTimeField(blank=True, null=True)),
                ("region", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="districts", to="lims.region")),
            ],
            options={"ordering": ["region__name", "name"]},
        ),
        migrations.CreateModel(
            name="Ward",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=200)),
                ("slug", models.SlugField(blank=True, default="", max_length=220)),
                ("source_path", models.CharField(max_length=500, unique=True)),
                ("source_url", models.URLField(max_length=800)),
                ("is_active", models.BooleanField(default=True)),
                ("last_synced_at", models.DateTimeField(blank=True, null=True)),
                ("district", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="wards", to="lims.district")),
            ],
            options={"ordering": ["district__region__name", "district__name", "name"]},
        ),
        migrations.CreateModel(
            name="Street",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=200)),
                ("slug", models.SlugField(blank=True, default="", max_length=220)),
                ("source_path", models.CharField(max_length=500, unique=True)),
                ("source_url", models.URLField(max_length=800)),
                ("is_active", models.BooleanField(default=True)),
                ("last_synced_at", models.DateTimeField(blank=True, null=True)),
                ("ward", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="streets", to="lims.ward")),
            ],
            options={"ordering": ["ward__district__region__name", "ward__district__name", "ward__name", "name"]},
        ),
        migrations.CreateModel(
            name="Postcode",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("code", models.CharField(max_length=16)),
                ("source_path", models.CharField(max_length=500, unique=True)),
                ("source_url", models.URLField(max_length=800)),
                ("is_active", models.BooleanField(default=True)),
                ("last_synced_at", models.DateTimeField(blank=True, null=True)),
                ("street", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="postcodes", to="lims.street")),
            ],
            options={"ordering": ["street__ward__district__region__country__name", "code"]},
        ),
        migrations.AddField(
            model_name="lab",
            name="country",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="labs", to="lims.country"),
        ),
        migrations.AddField(
            model_name="site",
            name="country",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="sites", to="lims.country"),
        ),
        migrations.AddConstraint(
            model_name="region",
            constraint=models.UniqueConstraint(fields=("country", "name"), name="uniq_lims_region_per_country"),
        ),
        migrations.AddConstraint(
            model_name="district",
            constraint=models.UniqueConstraint(fields=("region", "name"), name="uniq_lims_district_per_region"),
        ),
        migrations.AddConstraint(
            model_name="ward",
            constraint=models.UniqueConstraint(fields=("district", "name"), name="uniq_lims_ward_per_district"),
        ),
        migrations.AddConstraint(
            model_name="street",
            constraint=models.UniqueConstraint(fields=("ward", "name"), name="uniq_lims_street_per_ward"),
        ),
        migrations.AddConstraint(
            model_name="postcode",
            constraint=models.UniqueConstraint(fields=("street", "code"), name="uniq_lims_postcode_per_street"),
        ),
        migrations.RunPython(forwards_generalize_geography, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="lab",
            name="region",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="labs", to="lims.region"),
        ),
        migrations.AlterField(
            model_name="lab",
            name="district",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="labs", to="lims.district"),
        ),
        migrations.AlterField(
            model_name="lab",
            name="ward",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="labs", to="lims.ward"),
        ),
        migrations.AlterField(
            model_name="lab",
            name="street",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="labs", to="lims.street"),
        ),
        migrations.AlterField(
            model_name="site",
            name="region",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="sites", to="lims.region"),
        ),
        migrations.AlterField(
            model_name="site",
            name="district",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="sites", to="lims.district"),
        ),
        migrations.AlterField(
            model_name="site",
            name="ward",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="sites", to="lims.ward"),
        ),
        migrations.AlterField(
            model_name="site",
            name="street",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="sites", to="lims.street"),
        ),
        migrations.DeleteModel(name="TanzaniaStreet"),
        migrations.DeleteModel(name="TanzaniaWard"),
        migrations.DeleteModel(name="TanzaniaDistrict"),
        migrations.DeleteModel(name="TanzaniaRegion"),
    ]
