# Generated by hand for the batch and plate management slice.

import django.db.models.deletion
import uuid
from django.db import migrations, models


def seed_plate_layout_templates(apps, schema_editor):
    PlateLayoutTemplate = apps.get_model("lims", "PlateLayoutTemplate")
    defaults = [
        {
            "name": "96-well plate",
            "key": "96-well",
            "description": "Standard 8 x 12 plate layout for routine laboratory batches.",
            "rows": 8,
            "columns": 12,
            "is_active": True,
        },
        {
            "name": "384-well plate",
            "key": "384-well",
            "description": "High-density 16 x 24 plate layout for large processing runs.",
            "rows": 16,
            "columns": 24,
            "is_active": True,
        },
    ]
    for payload in defaults:
        PlateLayoutTemplate.objects.update_or_create(key=payload["key"], defaults=payload)


class Migration(migrations.Migration):

    dependencies = [
        ("lims", "0005_generalize_geography"),
    ]

    operations = [
        migrations.CreateModel(
            name="PlateLayoutTemplate",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=200)),
                ("key", models.SlugField(max_length=100, unique=True)),
                ("description", models.TextField(blank=True, default="")),
                ("rows", models.PositiveIntegerField(default=8)),
                ("columns", models.PositiveIntegerField(default=12)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["name"],
                "indexes": [models.Index(fields=["key"], name="lims_plate_layout_key_idx")],
            },
        ),
        migrations.CreateModel(
            name="ProcessingBatch",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("batch_identifier", models.CharField(max_length=80, unique=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("assigned", "Assigned"),
                            ("printed", "Printed"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="draft",
                        max_length=16,
                    ),
                ),
                ("notes", models.TextField(blank=True, default="")),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_by", models.CharField(blank=True, default="", max_length=100)),
                (
                    "lab",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="processing_batches",
                        to="lims.lab",
                    ),
                ),
                (
                    "sample_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="processing_batches",
                        to="lims.biospecimentype",
                    ),
                ),
                (
                    "site",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="processing_batches",
                        to="lims.site",
                    ),
                ),
                (
                    "study",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="processing_batches",
                        to="lims.study",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["batch_identifier"], name="lims_proc_batch_id_idx"),
                    models.Index(fields=["status", "-created_at"], name="lims_proc_batch_status_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="BatchPlate",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("plate_identifier", models.CharField(max_length=100, unique=True)),
                ("sequence_number", models.PositiveIntegerField(default=1)),
                ("label", models.CharField(blank=True, default="", max_length=100)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "batch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="plates",
                        to="lims.processingbatch",
                    ),
                ),
                (
                    "layout_template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="plates",
                        to="lims.platelayouttemplate",
                    ),
                ),
            ],
            options={
                "ordering": ["batch__batch_identifier", "sequence_number"],
                "indexes": [models.Index(fields=["batch", "sequence_number"], name="lims_batch_plate_seq_idx")],
            },
        ),
        migrations.CreateModel(
            name="BatchPlateAssignment",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("position_index", models.PositiveIntegerField(default=1)),
                ("well_label", models.CharField(max_length=8)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "biospecimen",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="plate_assignments",
                        to="lims.biospecimen",
                    ),
                ),
                (
                    "plate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assignments",
                        to="lims.batchplate",
                    ),
                ),
            ],
            options={"ordering": ["plate__plate_identifier", "position_index"]},
        ),
        migrations.AddConstraint(
            model_name="platelayouttemplate",
            constraint=models.UniqueConstraint(fields=("rows", "columns"), name="uniq_lims_plate_layout_dims"),
        ),
        migrations.AddConstraint(
            model_name="batchplate",
            constraint=models.UniqueConstraint(fields=("batch", "sequence_number"), name="uniq_lims_batch_plate_seq"),
        ),
        migrations.AddConstraint(
            model_name="batchplateassignment",
            constraint=models.UniqueConstraint(fields=("plate", "position_index"), name="uniq_lims_plate_assign_pos"),
        ),
        migrations.AddConstraint(
            model_name="batchplateassignment",
            constraint=models.UniqueConstraint(fields=("plate", "well_label"), name="uniq_lims_plate_assign_label"),
        ),
        migrations.AddConstraint(
            model_name="batchplateassignment",
            constraint=models.UniqueConstraint(fields=("plate", "biospecimen"), name="uniq_lims_plate_assign_spec"),
        ),
        migrations.RunPython(seed_plate_layout_templates, migrations.RunPython.noop),
    ]
