# Generated by hand for multi-study site associations.

from django.db import migrations, models


def forwards_copy_site_studies(apps, schema_editor):
    Site = apps.get_model("lims", "Site")
    for site in Site.objects.exclude(study_id=None):
        site.studies.add(site.study_id)


def reverse_copy_site_studies(apps, schema_editor):
    Site = apps.get_model("lims", "Site")
    for site in Site.objects.all():
        first_study = site.studies.order_by("name").first()
        site.study_id = first_study.id if first_study else None
        site.save(update_fields=["study"])


class Migration(migrations.Migration):

    dependencies = [
        ("lims", "0006_batch_plate_management"),
    ]

    operations = [
        migrations.AddField(
            model_name="site",
            name="studies",
            field=models.ManyToManyField(blank=True, related_name="linked_sites", to="lims.study"),
        ),
        migrations.RunPython(forwards_copy_site_studies, reverse_copy_site_studies),
    ]
