# Generated by hand for metadata vocabulary domains and default backfill.

import uuid

from django.db import migrations, models
import django.db.models.deletion


DEFAULT_DOMAIN_CODE = "general"


def forwards_create_default_domain(apps, schema_editor):
    MetadataVocabulary = apps.get_model("lims", "MetadataVocabulary")
    MetadataVocabularyDomain = apps.get_model("lims", "MetadataVocabularyDomain")
    domain, _ = MetadataVocabularyDomain.objects.get_or_create(
        code=DEFAULT_DOMAIN_CODE,
        defaults={
            "name": "General",
            "description": "Fallback domain for vocabularies created before functional categorization was introduced.",
            "is_active": True,
        },
    )
    MetadataVocabulary.objects.filter(domain_id__isnull=True).update(domain=domain)


def reverse_remove_default_domain(apps, schema_editor):
    MetadataVocabulary = apps.get_model("lims", "MetadataVocabulary")
    MetadataVocabularyDomain = apps.get_model("lims", "MetadataVocabularyDomain")
    default_domain = MetadataVocabularyDomain.objects.filter(code=DEFAULT_DOMAIN_CODE).first()
    if default_domain is None:
        return
    MetadataVocabulary.objects.filter(domain=default_domain).update(domain=None)
    default_domain.delete()


class Migration(migrations.Migration):

    dependencies = [
        ("lims", "0007_site_studies"),
    ]

    operations = [
        migrations.CreateModel(
            name="MetadataVocabularyDomain",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=200)),
                ("code", models.SlugField(max_length=100, unique=True)),
                ("description", models.TextField(blank=True, default="")),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.AddIndex(
            model_name="metadatavocabularydomain",
            index=models.Index(fields=["code"], name="lims_meta_vdom_code_idx"),
        ),
        migrations.AddField(
            model_name="metadatavocabulary",
            name="domain",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="vocabularies",
                to="lims.metadatavocabularydomain",
            ),
        ),
        migrations.RunPython(forwards_create_default_domain, reverse_remove_default_domain),
        migrations.AlterField(
            model_name="metadatavocabulary",
            name="domain",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="vocabularies",
                to="lims.metadatavocabularydomain",
            ),
        ),
        migrations.AddIndex(
            model_name="metadatavocabulary",
            index=models.Index(fields=["domain", "name"], name="lims_meta_vocab_dname_idx"),
        ),
    ]
