# Generated by hand for version-owned metadata fields.

from django.db import migrations, models
import django.db.models.deletion


def forwards_copy_field_definition_details(apps, schema_editor):
    MetadataSchemaField = apps.get_model("lims", "MetadataSchemaField")
    for field in MetadataSchemaField.objects.select_related("field_definition").all():
        definition = field.field_definition
        if definition is None:
            continue
        field.name = definition.name
        field.description = definition.description
        field.field_type = definition.field_type
        field.help_text = definition.help_text
        field.placeholder = definition.placeholder
        field.vocabulary_id = definition.vocabulary_id
        field.default_value = definition.default_value
        field.config = definition.config
        field.save(
            update_fields=[
                "name",
                "description",
                "field_type",
                "help_text",
                "placeholder",
                "vocabulary",
                "default_value",
                "config",
            ]
        )


class Migration(migrations.Migration):

    dependencies = [
        ("lims", "0008_metadata_vocabulary_domains"),
    ]

    operations = [
        migrations.AddField(
            model_name="metadataschema",
            name="purpose",
            field=models.CharField(blank=True, default="", max_length=200),
        ),
        migrations.AddField(
            model_name="metadataschemafield",
            name="config",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="metadataschemafield",
            name="default_value",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="metadataschemafield",
            name="description",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="metadataschemafield",
            name="field_type",
            field=models.CharField(
                choices=[
                    ("text", "Text"),
                    ("long_text", "Long Text"),
                    ("integer", "Integer"),
                    ("decimal", "Decimal"),
                    ("boolean", "Boolean"),
                    ("date", "Date"),
                    ("datetime", "Datetime"),
                    ("choice", "Choice"),
                    ("multi_choice", "Multi Choice"),
                ],
                default="text",
                max_length=32,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="metadataschemafield",
            name="help_text",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="metadataschemafield",
            name="name",
            field=models.CharField(default="", max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="metadataschemafield",
            name="placeholder",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="metadataschemafield",
            name="vocabulary",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="schema_fields",
                to="lims.metadatavocabulary",
            ),
        ),
        migrations.AlterField(
            model_name="metadataschemafield",
            name="field_definition",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="schema_fields",
                to="lims.metadatafielddefinition",
            ),
        ),
        migrations.RunPython(forwards_copy_field_definition_details, migrations.RunPython.noop),
    ]
