# Generated by Django 5.1.14 on 2026-03-20 01:21

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lims', '0009_version_owned_metadata_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkflowTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('code', models.SlugField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, default='')),
                ('purpose', models.CharField(blank=True, default='', max_length=200)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['code'], name='lims_wf_template_code_idx')],
            },
        ),
        migrations.CreateModel(
            name='WorkflowTemplateVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version_number', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('deprecated', 'Deprecated')], default='draft', max_length=16)),
                ('change_summary', models.CharField(blank=True, default='', max_length=255)),
                ('compiled_definition', models.JSONField(blank=True, default=dict)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='lims.workflowtemplate')),
            ],
            options={
                'ordering': ['template__name', '-version_number'],
            },
        ),
        migrations.CreateModel(
            name='WorkflowNodeTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('node_key', models.SlugField(max_length=100)),
                ('node_type', models.CharField(choices=[('start', 'Start'), ('start_handle', 'Start Handle'), ('view', 'View'), ('function', 'Function'), ('handle', 'Handle'), ('if', 'If'), ('switch', 'Switch'), ('split', 'Split'), ('split_first', 'Split First'), ('join', 'Join'), ('end', 'End')], max_length=32)),
                ('title', models.CharField(max_length=200)),
                ('summary', models.TextField(blank=True, default='')),
                ('position', models.PositiveIntegerField(default=0)),
                ('assignment_role', models.CharField(blank=True, default='', max_length=100)),
                ('permission_key', models.CharField(blank=True, default='', max_length=100)),
                ('requires_approval', models.BooleanField(default=False)),
                ('approval_role', models.CharField(blank=True, default='', max_length=100)),
                ('config', models.JSONField(blank=True, default=dict)),
                ('workflow_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nodes', to='lims.workflowtemplateversion')),
            ],
            options={
                'ordering': ['workflow_version__template__name', 'position', 'node_key'],
            },
        ),
        migrations.CreateModel(
            name='WorkflowEdgeTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('priority', models.PositiveIntegerField(default=0)),
                ('condition', models.JSONField(blank=True, default=dict)),
                ('source_node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_edges', to='lims.workflownodetemplate')),
                ('target_node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_edges', to='lims.workflownodetemplate')),
                ('workflow_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edges', to='lims.workflowtemplateversion')),
            ],
            options={
                'ordering': ['workflow_version__template__name', 'priority', 'source_node__node_key', 'target_node__node_key'],
            },
        ),
        migrations.CreateModel(
            name='WorkflowStepBinding',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('binding_type', models.CharField(choices=[('full_schema', 'Full Schema'), ('ui_step', 'Ui Step'), ('field_set', 'Field Set')], default='full_schema', max_length=32)),
                ('ui_step', models.SlugField(blank=True, default='', max_length=100)),
                ('field_keys', models.JSONField(blank=True, default=list)),
                ('is_required', models.BooleanField(default=True)),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='step_bindings', to='lims.workflownodetemplate')),
                ('schema_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workflow_step_bindings', to='lims.metadataschemaversion')),
            ],
            options={
                'ordering': ['node__workflow_version__template__name', 'node__position', 'schema_version__schema__name'],
                'constraints': [models.UniqueConstraint(fields=('node', 'schema_version', 'binding_type', 'ui_step'), name='uniq_lims_wf_step_binding_scope')],
            },
        ),
        migrations.AddConstraint(
            model_name='workflowtemplateversion',
            constraint=models.UniqueConstraint(fields=('template', 'version_number'), name='uniq_lims_wf_template_version_number'),
        ),
        migrations.AddConstraint(
            model_name='workflownodetemplate',
            constraint=models.UniqueConstraint(fields=('workflow_version', 'node_key'), name='uniq_lims_wf_node_per_version'),
        ),
        migrations.AddConstraint(
            model_name='workflowedgetemplate',
            constraint=models.UniqueConstraint(fields=('workflow_version', 'source_node', 'target_node', 'priority'), name='uniq_lims_wf_edge_priority'),
        ),
    ]
