# Generated by Django 5.1.14 on 2026-03-20 04:43

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_printtemplate'),
        ('lims', '0010_workflowtemplate_workflowtemplateversion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OperationDefinition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('code', models.SlugField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, default='')),
                ('purpose', models.CharField(blank=True, default='', max_length=200)),
                ('module_scope', models.CharField(choices=[('lims', 'Lims'), ('edcs', 'Edcs')], default='lims', max_length=16)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['code'], name='lims_op_definition_code_idx'), models.Index(fields=['module_scope', 'is_active'], name='lims_op_definition_scope_idx')],
            },
        ),
        migrations.CreateModel(
            name='OperationVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version_number', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('deprecated', 'Deprecated')], default='draft', max_length=16)),
                ('change_summary', models.CharField(blank=True, default='', max_length=255)),
                ('sop_version_label', models.CharField(blank=True, default='', max_length=64)),
                ('sop_effective_date', models.DateField(blank=True, null=True)),
                ('runtime_defaults', models.JSONField(blank=True, default=dict)),
                ('definition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='lims.operationdefinition')),
                ('sop_document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operation_versions', to='core.collaborationdocument')),
                ('sop_document_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operation_versions', to='core.collaborationdocumentversion')),
                ('workflow_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='operation_versions', to='lims.workflowtemplateversion')),
            ],
            options={
                'ordering': ['definition__name', '-version_number'],
            },
        ),
        migrations.CreateModel(
            name='OperationRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('paused', 'Paused'), ('completed', 'Completed'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], default='active', max_length=16)),
                ('source_mode', models.CharField(choices=[('single', 'Single'), ('batch', 'Batch'), ('edc_import', 'Edc Import'), ('manual', 'Manual')], default='single', max_length=16)),
                ('source_reference', models.CharField(blank=True, default='', max_length=100)),
                ('subject_identifier', models.CharField(blank=True, default='', max_length=100)),
                ('external_identifier', models.CharField(blank=True, default='', max_length=100)),
                ('initiated_by', models.CharField(blank=True, default='', max_length=200)),
                ('outcome', models.CharField(blank=True, default='', max_length=64)),
                ('context', models.JSONField(blank=True, default=dict)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('biospecimen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operation_runs', to='lims.biospecimen')),
                ('manifest', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operation_runs', to='lims.accessioningmanifest')),
                ('manifest_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operation_runs', to='lims.accessioningmanifestitem')),
                ('workflow_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='operation_runs', to='lims.workflowtemplateversion')),
                ('operation_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='runs', to='lims.operationversion')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TaskRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('awaiting_approval', 'Awaiting Approval'), ('completed', 'Completed'), ('skipped', 'Skipped'), ('cancelled', 'Cancelled')], default='open', max_length=24)),
                ('assignment_role', models.CharField(blank=True, default='', max_length=100)),
                ('assignee', models.CharField(blank=True, default='', max_length=200)),
                ('permission_key', models.CharField(blank=True, default='', max_length=100)),
                ('requires_approval', models.BooleanField(default=False)),
                ('approval_role', models.CharField(blank=True, default='', max_length=100)),
                ('outcome', models.CharField(blank=True, default='', max_length=64)),
                ('input_context', models.JSONField(blank=True, default=dict)),
                ('output_data', models.JSONField(blank=True, default=dict)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('node_template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='task_runs', to='lims.workflownodetemplate')),
                ('operation_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='lims.operationrun')),
            ],
            options={
                'ordering': ['operation_run__created_at', 'node_template__position', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='SubmissionRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('submission_index', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('finalized', 'Finalized')], default='submitted', max_length=16)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('submitted_by', models.CharField(blank=True, default='', max_length=200)),
                ('submitted_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('task_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='lims.taskrun')),
            ],
            options={
                'ordering': ['task_run__created_at', 'submission_index'],
            },
        ),
        migrations.CreateModel(
            name='MaterialUsageRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('action', models.CharField(max_length=64)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('biospecimen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='material_usages', to='lims.biospecimen')),
                ('discrepancy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='material_usages', to='lims.receivingdiscrepancy')),
                ('manifest', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='material_usages', to='lims.accessioningmanifest')),
                ('manifest_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='material_usages', to='lims.accessioningmanifestitem')),
                ('receiving_event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='material_usages', to='lims.receivingevent')),
                ('operation_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='material_usages', to='lims.operationrun')),
                ('task_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='material_usages', to='lims.taskrun')),
            ],
            options={
                'ordering': ['operation_run__created_at', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='ApprovalRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('outcome', models.CharField(choices=[('approved', 'Approved'), ('rejected', 'Rejected')], max_length=16)),
                ('meaning', models.CharField(blank=True, default='', max_length=200)),
                ('approver_role', models.CharField(blank=True, default='', max_length=100)),
                ('approved_by', models.CharField(blank=True, default='', max_length=200)),
                ('comments', models.TextField(blank=True, default='')),
                ('approved_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('operation_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approvals', to='lims.operationrun')),
                ('task_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='approvals', to='lims.taskrun')),
            ],
            options={
                'ordering': ['approved_at', 'created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='operationversion',
            index=models.Index(fields=['status', '-version_number'], name='lims_op_version_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='operationversion',
            constraint=models.UniqueConstraint(fields=('definition', 'version_number'), name='uniq_lims_operation_version_number'),
        ),
        migrations.AddIndex(
            model_name='operationrun',
            index=models.Index(fields=['status', '-created_at'], name='lims_op_run_status_idx'),
        ),
        migrations.AddIndex(
            model_name='operationrun',
            index=models.Index(fields=['source_mode', '-created_at'], name='lims_op_run_source_idx'),
        ),
        migrations.AddIndex(
            model_name='taskrun',
            index=models.Index(fields=['status', '-created_at'], name='lims_task_run_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='taskrun',
            constraint=models.UniqueConstraint(fields=('operation_run', 'node_template'), name='uniq_lims_task_run_node'),
        ),
        migrations.AddConstraint(
            model_name='submissionrecord',
            constraint=models.UniqueConstraint(fields=('task_run', 'submission_index'), name='uniq_lims_submission_index'),
        ),
        migrations.AddIndex(
            model_name='materialusagerecord',
            index=models.Index(fields=['action', '-created_at'], name='lims_material_usage_action_idx'),
        ),
        migrations.AddIndex(
            model_name='approvalrecord',
            index=models.Index(fields=['outcome', '-approved_at'], name='lims_approval_outcome_idx'),
        ),
    ]
