# Generated by Django 5.1.14 on 2026-03-20 10:26

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lims', '0012_qcresult'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryMaterial',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('code', models.SlugField(max_length=120, unique=True)),
                ('category', models.CharField(choices=[('reagent', 'Reagent'), ('kit', 'Kit'), ('consumable', 'Consumable'), ('media', 'Media'), ('label', 'Label'), ('other', 'Other')], default='consumable', max_length=32)),
                ('description', models.TextField(blank=True, default='')),
                ('default_unit', models.CharField(blank=True, default='', max_length=32)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['category', 'name'], name='lims_inv_mat_cat_idx')],
            },
        ),
        migrations.CreateModel(
            name='InventoryLot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lot_number', models.CharField(max_length=120)),
                ('vendor', models.CharField(blank=True, default='', max_length=200)),
                ('received_on', models.DateField(blank=True, null=True)),
                ('expires_on', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('initial_quantity', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('on_hand_quantity', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('unit_of_measure', models.CharField(blank=True, default='', max_length=32)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('lab', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventory_lots', to='lims.lab')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lots', to='lims.inventorymaterial')),
            ],
            options={
                'ordering': ['material__name', 'lot_number'],
            },
        ),
        migrations.CreateModel(
            name='StorageLocation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('code', models.SlugField(max_length=120)),
                ('level', models.CharField(choices=[('facility', 'Facility'), ('area', 'Area'), ('equipment', 'Equipment'), ('container', 'Container'), ('position', 'Position')], max_length=32)),
                ('temperature_zone', models.CharField(blank=True, choices=[('ambient', 'Ambient'), ('cold_room', 'Cold Room'), ('fridge', 'Fridge'), ('freezer_minus20', 'Freezer Minus20'), ('freezer_minus80', 'Freezer Minus80'), ('liquid_nitrogen', 'Liquid Nitrogen')], default='', max_length=32)),
                ('capacity', models.PositiveIntegerField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('lab', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='storage_locations', to='lims.lab')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='lims.storagelocation')),
            ],
            options={
                'ordering': ['lab__name', 'level', 'name'],
            },
        ),
        migrations.CreateModel(
            name='InventoryTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('transaction_type', models.CharField(choices=[('receipt', 'Receipt'), ('adjustment', 'Adjustment'), ('reservation', 'Reservation'), ('release', 'Release'), ('consumption', 'Consumption'), ('transfer', 'Transfer'), ('disposal', 'Disposal'), ('expiry', 'Expiry')], max_length=32)),
                ('quantity_delta', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('resulting_quantity', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('notes', models.TextField(blank=True, default='')),
                ('recorded_by', models.CharField(blank=True, default='', max_length=200)),
                ('biospecimen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_transactions', to='lims.biospecimen')),
                ('biospecimen_pool', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_transactions', to='lims.biospecimenpool')),
                ('lot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='lims.inventorylot')),
                ('material_usage_record', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_transactions', to='lims.materialusagerecord')),
                ('operation_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_transactions', to='lims.operationrun')),
                ('submission_record', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_transactions', to='lims.submissionrecord')),
                ('task_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_transactions', to='lims.taskrun')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inventory_transactions', to='lims.storagelocation')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='inventorylot',
            name='storage_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inventory_lots', to='lims.storagelocation'),
        ),
        migrations.CreateModel(
            name='BiospecimenStorageRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reason', models.CharField(choices=[('received', 'Received'), ('placed', 'Placed'), ('moved', 'Moved'), ('reserved', 'Reserved'), ('released', 'Released'), ('retrieved', 'Retrieved'), ('archived', 'Archived')], max_length=32)),
                ('quantity_snapshot', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('quantity_unit', models.CharField(blank=True, default='', max_length=32)),
                ('notes', models.TextField(blank=True, default='')),
                ('placed_by', models.CharField(blank=True, default='', max_length=200)),
                ('biospecimen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='storage_records', to='lims.biospecimen')),
                ('biospecimen_pool', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='storage_records', to='lims.biospecimenpool')),
                ('operation_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='storage_records', to='lims.operationrun')),
                ('submission_record', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='storage_records', to='lims.submissionrecord')),
                ('task_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='storage_records', to='lims.taskrun')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='biospecimen_records', to='lims.storagelocation')),
                ('previous_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='next_biospecimen_records', to='lims.storagelocation')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='storagelocation',
            index=models.Index(fields=['lab', 'level'], name='lims_storage_lab_level_idx'),
        ),
        migrations.AddIndex(
            model_name='storagelocation',
            index=models.Index(fields=['parent', 'name'], name='lims_storage_parent_name_idx'),
        ),
        migrations.AddConstraint(
            model_name='storagelocation',
            constraint=models.UniqueConstraint(fields=('parent', 'code'), name='uniq_lims_storage_parent'),
        ),
        migrations.AddConstraint(
            model_name='storagelocation',
            constraint=models.UniqueConstraint(condition=models.Q(('parent__isnull', True)), fields=('lab', 'code'), name='uniq_lims_storage_top'),
        ),
        migrations.AddIndex(
            model_name='inventorytransaction',
            index=models.Index(fields=['lot', '-created_at'], name='lims_inv_txn_lot_idx'),
        ),
        migrations.AddIndex(
            model_name='inventorytransaction',
            index=models.Index(fields=['transaction_type', '-created_at'], name='lims_inv_txn_type_idx'),
        ),
        migrations.AddIndex(
            model_name='inventorylot',
            index=models.Index(fields=['material', 'lot_number'], name='lims_inv_lot_lookup_idx'),
        ),
        migrations.AddIndex(
            model_name='inventorylot',
            index=models.Index(fields=['lab', '-created_at'], name='lims_inv_lot_lab_idx'),
        ),
        migrations.AddConstraint(
            model_name='inventorylot',
            constraint=models.UniqueConstraint(fields=('material', 'lot_number'), name='uniq_lims_inv_lot'),
        ),
        migrations.AddIndex(
            model_name='biospecimenstoragerecord',
            index=models.Index(fields=['biospecimen', '-created_at'], name='lims_storage_specimen_idx'),
        ),
        migrations.AddIndex(
            model_name='biospecimenstoragerecord',
            index=models.Index(fields=['biospecimen_pool', '-created_at'], name='lims_storage_pool_idx'),
        ),
        migrations.AddIndex(
            model_name='biospecimenstoragerecord',
            index=models.Index(fields=['location', '-created_at'], name='lims_storage_location_idx'),
        ),
        migrations.AddConstraint(
            model_name='biospecimenstoragerecord',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('biospecimen__isnull', False), ('biospecimen_pool__isnull', True)), models.Q(('biospecimen__isnull', True), ('biospecimen_pool__isnull', False)), _connector='OR'), name='lims_storage_one_artifact'),
        ),
    ]
