# Generated by Django 5.1.14 on 2026-03-20 13:52

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lims', '0013_inventorymaterial_inventorylot_storagelocation_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormPackage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('code', models.SlugField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, default='')),
                ('purpose', models.CharField(blank=True, default='', max_length=200)),
                ('module_scope', models.CharField(choices=[('shared', 'Shared'), ('lims', 'Lims'), ('edcs', 'Edcs')], default='shared', max_length=16)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['code'], name='lims_form_pkg_code_idx'), models.Index(fields=['module_scope', 'is_active'], name='lims_form_pkg_scope_idx')],
            },
        ),
        migrations.CreateModel(
            name='FormPackageChoiceList',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('list_key', models.SlugField(max_length=100)),
                ('oid', models.CharField(max_length=160)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('position', models.PositiveIntegerField(default=0)),
                ('vocabulary', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='form_choice_lists', to='lims.metadatavocabulary')),
            ],
            options={
                'ordering': ['version__package__name', 'position', 'list_key'],
            },
        ),
        migrations.CreateModel(
            name='FormPackageVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version_number', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('deprecated', 'Deprecated')], default='draft', max_length=16)),
                ('change_summary', models.CharField(blank=True, default='', max_length=255)),
                ('compiler_context', models.JSONField(blank=True, default=dict)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='lims.formpackage')),
                ('source_schema_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='form_package_versions', to='lims.metadataschemaversion')),
            ],
            options={
                'ordering': ['package__name', '-version_number'],
            },
        ),
        migrations.CreateModel(
            name='FormPackageSourceArtifact',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.CharField(choices=[('source', 'Source'), ('export', 'Export')], default='source', max_length=16)),
                ('artifact_type', models.CharField(choices=[('xlsx', 'Xlsx'), ('odm_xml', 'Odm Xml'), ('json', 'Json')], max_length=16)),
                ('filename', models.CharField(max_length=255)),
                ('content_type', models.CharField(blank=True, default='', max_length=120)),
                ('checksum', models.CharField(blank=True, default='', max_length=128)),
                ('storage_key', models.CharField(blank=True, default='', max_length=400)),
                ('artifact_metadata', models.JSONField(blank=True, default=dict)),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_artifacts', to='lims.formpackageversion')),
            ],
            options={
                'ordering': ['version__package__name', 'created_at', 'filename'],
            },
        ),
        migrations.CreateModel(
            name='FormPackageSection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('section_key', models.SlugField(max_length=100)),
                ('oid', models.CharField(max_length=160)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('position', models.PositiveIntegerField(default=0)),
                ('config', models.JSONField(blank=True, default=dict)),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='lims.formpackageversion')),
            ],
            options={
                'ordering': ['version__package__name', 'version__version_number', 'position', 'section_key'],
            },
        ),
        migrations.CreateModel(
            name='FormPackageProjection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('projection', models.JSONField(blank=True, default=dict)),
                ('version', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='compiled_projection', to='lims.formpackageversion')),
            ],
            options={
                'ordering': ['version__package__name'],
            },
        ),
        migrations.CreateModel(
            name='FormPackageItemGroup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('group_key', models.SlugField(max_length=100)),
                ('oid', models.CharField(max_length=160)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('position', models.PositiveIntegerField(default=0)),
                ('repeats', models.BooleanField(default=False)),
                ('config', models.JSONField(blank=True, default=dict)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_groups', to='lims.formpackagesection')),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_groups', to='lims.formpackageversion')),
            ],
            options={
                'ordering': ['version__package__name', 'position', 'group_key'],
            },
        ),
        migrations.CreateModel(
            name='FormPackageItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('item_key', models.SlugField(max_length=100)),
                ('oid', models.CharField(max_length=160)),
                ('question_text', models.CharField(max_length=200)),
                ('prompt_text', models.TextField(blank=True, default='')),
                ('field_type', models.CharField(choices=[('text', 'Text'), ('long_text', 'Long Text'), ('integer', 'Integer'), ('decimal', 'Decimal'), ('boolean', 'Boolean'), ('date', 'Date'), ('datetime', 'Datetime'), ('choice', 'Choice'), ('multi_choice', 'Multi Choice')], max_length=32)),
                ('help_text', models.CharField(blank=True, default='', max_length=255)),
                ('placeholder', models.CharField(blank=True, default='', max_length=255)),
                ('default_value', models.JSONField(blank=True, null=True)),
                ('position', models.PositiveIntegerField(default=0)),
                ('required', models.BooleanField(default=False)),
                ('validation_rules', models.JSONField(blank=True, default=dict)),
                ('config', models.JSONField(blank=True, default=dict)),
                ('source_field_key', models.SlugField(blank=True, default='', max_length=100)),
                ('choice_list', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='lims.formpackagechoicelist')),
                ('item_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='lims.formpackageitemgroup')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='lims.formpackagesection')),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='lims.formpackageversion')),
            ],
            options={
                'ordering': ['version__package__name', 'section__position', 'position', 'item_key'],
            },
        ),
        migrations.CreateModel(
            name='FormPackageCompilerDiagnostic',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('severity', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('error', 'Error')], max_length=16)),
                ('stage', models.CharField(choices=[('ingest', 'Ingest'), ('normalize', 'Normalize'), ('validate', 'Validate'), ('compile', 'Compile'), ('export', 'Export')], max_length=16)),
                ('code', models.CharField(max_length=64)),
                ('pointer', models.CharField(blank=True, default='', max_length=200)),
                ('message', models.TextField()),
                ('details', models.JSONField(blank=True, default=dict)),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compiler_diagnostics', to='lims.formpackageversion')),
            ],
            options={
                'ordering': ['version__package__name', 'created_at', 'severity', 'code'],
            },
        ),
        migrations.AddField(
            model_name='formpackagechoicelist',
            name='version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choice_lists', to='lims.formpackageversion'),
        ),
        migrations.CreateModel(
            name='FormPackageChoice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('value', models.CharField(max_length=100)),
                ('label', models.CharField(max_length=200)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('choice_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='lims.formpackagechoicelist')),
            ],
            options={
                'ordering': ['choice_list__title', 'sort_order', 'label'],
                'constraints': [models.UniqueConstraint(fields=('choice_list', 'value'), name='uniq_lims_form_choice_val')],
            },
        ),
        migrations.AddIndex(
            model_name='formpackageversion',
            index=models.Index(fields=['status', '-version_number'], name='lims_form_pkg_ver_stat_idx'),
        ),
        migrations.AddConstraint(
            model_name='formpackageversion',
            constraint=models.UniqueConstraint(fields=('package', 'version_number'), name='uniq_lims_form_pkg_ver_no'),
        ),
        migrations.AddIndex(
            model_name='formpackagesourceartifact',
            index=models.Index(fields=['version', 'role'], name='lims_form_art_ver_role_idx'),
        ),
        migrations.AddConstraint(
            model_name='formpackagesection',
            constraint=models.UniqueConstraint(fields=('version', 'section_key'), name='uniq_lims_form_sec_key'),
        ),
        migrations.AddConstraint(
            model_name='formpackagesection',
            constraint=models.UniqueConstraint(fields=('version', 'oid'), name='uniq_lims_form_sec_oid'),
        ),
        migrations.AddConstraint(
            model_name='formpackageitemgroup',
            constraint=models.UniqueConstraint(fields=('version', 'group_key'), name='uniq_lims_form_grp_key'),
        ),
        migrations.AddConstraint(
            model_name='formpackageitemgroup',
            constraint=models.UniqueConstraint(fields=('version', 'oid'), name='uniq_lims_form_grp_oid'),
        ),
        migrations.AddConstraint(
            model_name='formpackageitem',
            constraint=models.UniqueConstraint(fields=('version', 'item_key'), name='uniq_lims_form_item_key'),
        ),
        migrations.AddConstraint(
            model_name='formpackageitem',
            constraint=models.UniqueConstraint(fields=('version', 'oid'), name='uniq_lims_form_item_oid'),
        ),
        migrations.AddIndex(
            model_name='formpackagecompilerdiagnostic',
            index=models.Index(fields=['version', 'severity'], name='lims_form_diag_ver_sev_idx'),
        ),
        migrations.AddConstraint(
            model_name='formpackagechoicelist',
            constraint=models.UniqueConstraint(fields=('version', 'list_key'), name='uniq_lims_form_cl_key'),
        ),
        migrations.AddConstraint(
            model_name='formpackagechoicelist',
            constraint=models.UniqueConstraint(fields=('version', 'oid'), name='uniq_lims_form_cl_oid'),
        ),
    ]
