from django.urls import path

from .views import (
    lims_accessioning_manifest_detail,
    lims_accessioning_manifest_item_receive,
    lims_accessioning_manifest_report,
    lims_accessioning_manifest_submit,
    lims_accessioning_manifests,
    lims_accessioning_receive_single,
    lims_biospecimen_aliquots,
    lims_biospecimen_detail,
    lims_biospecimen_pool_detail,
    lims_biospecimen_pool_storage_records,
    lims_biospecimen_pool_transition,
    lims_biospecimen_pools,
    lims_biospecimen_storage_records,
    lims_biospecimen_transition,
    lims_biospecimen_type_detail,
    lims_biospecimen_types,
    lims_biospecimens,
    lims_dashboard_summary,
    lims_form_package_detail,
    lims_form_package_version_detail,
    lims_form_package_version_publish,
    lims_form_package_versions,
    lims_form_packages,
    lims_metadata_field_definition_detail,
    lims_metadata_field_definitions,
    lims_metadata_schema_bindings,
    lims_metadata_schema_detail,
    lims_metadata_schema_version_detail,
    lims_metadata_schema_version_publish,
    lims_metadata_schema_versions,
    lims_metadata_schemas,
    lims_metadata_validate,
    lims_metadata_vocabulary_domain_detail,
    lims_metadata_vocabulary_domains,
    lims_metadata_vocabulary_detail,
    lims_metadata_vocabulary_items,
    lims_metadata_vocabulary_provision_defaults,
    lims_metadata_vocabularies,
    lims_operation_detail,
    lims_operation_run_detail,
    lims_operation_run_qc_results,
    lims_operation_runs,
    lims_operation_task_approve,
    lims_operation_task_submit,
    lims_operation_version_detail,
    lims_operation_version_publish,
    lims_operation_versions,
    lims_operations,
    lims_inventory_lot_detail,
    lims_inventory_lot_transactions,
    lims_inventory_lots,
    lims_inventory_material_detail,
    lims_inventory_materials,
    lims_permissions_summary,
    lims_plate_layout_detail,
    lims_plate_layouts,
    lims_processing_batch_detail,
    lims_processing_batch_transition,
    lims_processing_batch_worksheet,
    lims_processing_batch_worksheet_print_job,
    lims_processing_batches,
    lims_reference_address_sync_runs,
    lims_reference_lab_detail,
    lims_reference_labs,
    lims_reference_select_options,
    lims_reference_site_detail,
    lims_reference_sites,
    lims_reference_studies,
    lims_reference_study_detail,
    lims_receiving_discrepancies,
    lims_storage_location_detail,
    lims_storage_locations,
    lims_workflow_template_detail,
    lims_workflow_template_version_detail,
    lims_workflow_template_version_publish,
    lims_workflow_template_versions,
    lims_workflow_templates,
)

app_name = 'lims'


urlpatterns = [
    path("accessioning/manifests", lims_accessioning_manifests, name="accessioning_manifests"),
    path(
        "accessioning/manifests/<uuid:manifest_id>",
        lims_accessioning_manifest_detail,
        name="accessioning_manifest_detail",
    ),
    path(
        "accessioning/manifests/<uuid:manifest_id>/submit",
        lims_accessioning_manifest_submit,
        name="accessioning_manifest_submit",
    ),
    path(
        "accessioning/manifests/<uuid:manifest_id>/items/<uuid:item_id>/receive",
        lims_accessioning_manifest_item_receive,
        name="accessioning_manifest_item_receive",
    ),
    path(
        "accessioning/manifests/<uuid:manifest_id>/report",
        lims_accessioning_manifest_report,
        name="accessioning_manifest_report",
    ),
    path("accessioning/receive-single", lims_accessioning_receive_single, name="accessioning_receive_single"),
    path("biospecimens", lims_biospecimens, name="biospecimens"),
    path("biospecimens/<uuid:specimen_id>", lims_biospecimen_detail, name="biospecimen_detail"),
    path(
        "biospecimens/<uuid:specimen_id>/storage-records",
        lims_biospecimen_storage_records,
        name="biospecimen_storage_records",
    ),
    path(
        "biospecimens/<uuid:specimen_id>/aliquots",
        lims_biospecimen_aliquots,
        name="biospecimen_aliquots",
    ),
    path(
        "biospecimens/<uuid:specimen_id>/transition",
        lims_biospecimen_transition,
        name="biospecimen_transition",
    ),
    path("biospecimen-pools", lims_biospecimen_pools, name="biospecimen_pools"),
    path("biospecimen-pools/<uuid:pool_id>", lims_biospecimen_pool_detail, name="biospecimen_pool_detail"),
    path(
        "biospecimen-pools/<uuid:pool_id>/storage-records",
        lims_biospecimen_pool_storage_records,
        name="biospecimen_pool_storage_records",
    ),
    path(
        "biospecimen-pools/<uuid:pool_id>/transition",
        lims_biospecimen_pool_transition,
        name="biospecimen_pool_transition",
    ),
    path("biospecimen-types", lims_biospecimen_types, name="biospecimen_types"),
    path("biospecimen-types/<uuid:sample_type_id>", lims_biospecimen_type_detail, name="biospecimen_type_detail"),
    path("plate-layouts", lims_plate_layouts, name="plate_layouts"),
    path("plate-layouts/<uuid:layout_id>", lims_plate_layout_detail, name="plate_layout_detail"),
    path("processing-batches", lims_processing_batches, name="processing_batches"),
    path("processing-batches/<uuid:batch_id>", lims_processing_batch_detail, name="processing_batch_detail"),
    path(
        "processing-batches/<uuid:batch_id>/transition",
        lims_processing_batch_transition,
        name="processing_batch_transition",
    ),
    path(
        "processing-batches/<uuid:batch_id>/worksheet",
        lims_processing_batch_worksheet,
        name="processing_batch_worksheet",
    ),
    path(
        "processing-batches/<uuid:batch_id>/worksheet-print-job",
        lims_processing_batch_worksheet_print_job,
        name="processing_batch_worksheet_print_job",
    ),
    path("metadata/bindings", lims_metadata_schema_bindings, name="metadata_bindings"),
    path("form-packages", lims_form_packages, name="form_packages"),
    path("form-packages/<uuid:package_id>", lims_form_package_detail, name="form_package_detail"),
    path("form-packages/<uuid:package_id>/versions", lims_form_package_versions, name="form_package_versions"),
    path(
        "form-packages/<uuid:package_id>/versions/<uuid:version_id>",
        lims_form_package_version_detail,
        name="form_package_version_detail",
    ),
    path(
        "form-packages/<uuid:package_id>/versions/<uuid:version_id>/publish",
        lims_form_package_version_publish,
        name="form_package_version_publish",
    ),
    path("metadata/field-definitions", lims_metadata_field_definitions, name="metadata_field_definitions"),
    path(
        "metadata/field-definitions/<uuid:definition_id>",
        lims_metadata_field_definition_detail,
        name="metadata_field_definition_detail",
    ),
    path("metadata/schemas", lims_metadata_schemas, name="metadata_schemas"),
    path("metadata/schemas/<uuid:schema_id>", lims_metadata_schema_detail, name="metadata_schema_detail"),
    path("metadata/schemas/<uuid:schema_id>/versions", lims_metadata_schema_versions, name="metadata_schema_versions"),
    path(
        "metadata/schemas/<uuid:schema_id>/versions/<uuid:version_id>",
        lims_metadata_schema_version_detail,
        name="metadata_schema_version_detail",
    ),
    path(
        "metadata/schemas/<uuid:schema_id>/versions/<uuid:version_id>/publish",
        lims_metadata_schema_version_publish,
        name="metadata_schema_version_publish",
    ),
    path("metadata/validate", lims_metadata_validate, name="metadata_validate"),
    path("metadata/vocabulary-domains", lims_metadata_vocabulary_domains, name="metadata_vocabulary_domains"),
    path(
        "metadata/vocabulary-domains/<uuid:domain_id>",
        lims_metadata_vocabulary_domain_detail,
        name="metadata_vocabulary_domain_detail",
    ),
    path("metadata/vocabularies", lims_metadata_vocabularies, name="metadata_vocabularies"),
    path(
        "metadata/vocabularies/provision-defaults",
        lims_metadata_vocabulary_provision_defaults,
        name="metadata_vocabulary_provision_defaults",
    ),
    path("metadata/vocabularies/<uuid:vocabulary_id>", lims_metadata_vocabulary_detail, name="metadata_vocabulary_detail"),
    path(
        "metadata/vocabularies/<uuid:vocabulary_id>/items",
        lims_metadata_vocabulary_items,
        name="metadata_vocabulary_items",
    ),
    path("storage/locations", lims_storage_locations, name="storage_locations"),
    path("storage/locations/<uuid:location_id>", lims_storage_location_detail, name="storage_location_detail"),
    path("inventory/materials", lims_inventory_materials, name="inventory_materials"),
    path("inventory/materials/<uuid:material_id>", lims_inventory_material_detail, name="inventory_material_detail"),
    path("inventory/lots", lims_inventory_lots, name="inventory_lots"),
    path("inventory/lots/<uuid:lot_id>", lims_inventory_lot_detail, name="inventory_lot_detail"),
    path(
        "inventory/lots/<uuid:lot_id>/transactions",
        lims_inventory_lot_transactions,
        name="inventory_lot_transactions",
    ),
    path("operations", lims_operations, name="operations"),
    path("operations/<uuid:operation_id>", lims_operation_detail, name="operation_detail"),
    path(
        "operations/<uuid:operation_id>/versions",
        lims_operation_versions,
        name="operation_versions",
    ),
    path(
        "operations/<uuid:operation_id>/versions/<uuid:version_id>",
        lims_operation_version_detail,
        name="operation_version_detail",
    ),
    path(
        "operations/<uuid:operation_id>/versions/<uuid:version_id>/publish",
        lims_operation_version_publish,
        name="operation_version_publish",
    ),
    path("operations/<uuid:operation_id>/runs", lims_operation_runs, name="operation_runs"),
    path(
        "operations/<uuid:operation_id>/runs/<uuid:run_id>",
        lims_operation_run_detail,
        name="operation_run_detail",
    ),
    path(
        "operations/<uuid:operation_id>/runs/<uuid:run_id>/qc-results",
        lims_operation_run_qc_results,
        name="operation_run_qc_results",
    ),
    path(
        "operations/<uuid:operation_id>/runs/<uuid:run_id>/tasks/<uuid:task_id>/submit",
        lims_operation_task_submit,
        name="operation_task_submit",
    ),
    path(
        "operations/<uuid:operation_id>/runs/<uuid:run_id>/tasks/<uuid:task_id>/approve",
        lims_operation_task_approve,
        name="operation_task_approve",
    ),
    path("workflow-config/templates", lims_workflow_templates, name="workflow_templates"),
    path("workflow-config/templates/<uuid:template_id>", lims_workflow_template_detail, name="workflow_template_detail"),
    path(
        "workflow-config/templates/<uuid:template_id>/versions",
        lims_workflow_template_versions,
        name="workflow_template_versions",
    ),
    path(
        "workflow-config/templates/<uuid:template_id>/versions/<uuid:version_id>",
        lims_workflow_template_version_detail,
        name="workflow_template_version_detail",
    ),
    path(
        "workflow-config/templates/<uuid:template_id>/versions/<uuid:version_id>/publish",
        lims_workflow_template_version_publish,
        name="workflow_template_version_publish",
    ),
    path("reference/address-sync-runs", lims_reference_address_sync_runs, name="reference_address_sync_runs"),
    path("reference/labs", lims_reference_labs, name="reference_labs"),
    path("reference/labs/<uuid:lab_id>", lims_reference_lab_detail, name="reference_lab_detail"),
    path("reference/select-options", lims_reference_select_options, name="reference_select_options"),
    path("reference/sites", lims_reference_sites, name="reference_sites"),
    path("reference/sites/<uuid:site_id>", lims_reference_site_detail, name="reference_site_detail"),
    path("reference/studies", lims_reference_studies, name="reference_studies"),
    path("reference/studies/<uuid:study_id>", lims_reference_study_detail, name="reference_study_detail"),
    path("receiving/discrepancies", lims_receiving_discrepancies, name="receiving_discrepancies"),
    path('permissions', lims_permissions_summary, name='permissions'),
    path('summary', lims_dashboard_summary, name='summary'),
]
