"""
URL configuration for config project.

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/5.0/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  path('', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  path('', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.urls import include, path
    2. Add a URL to urlpatterns:  path('blog/', include('blog.urls'))
"""
from django.contrib import admin
from django.urls import path

from core.views import (
    access_request_decision,
    access_requests,
    asset_classifications,
    asset_detail,
    asset_contracts,
    asset_version_publish,
    asset_versions,
    assets,
    asset_glossary_term_link,
    agent_runs,
    agent_run_transition,
    contract_activate,
    classification_activate,
    classification_deprecate,
    classification_detail,
    classifications,
    collaboration_document_detail,
    collaboration_document_session,
    collaboration_document_versions,
    collaboration_documents,
    connector_run_cancel,
    connector_runs,
    contract_deprecate,
    contract_detail,
    contracts,
    data_product_activate,
    data_product_detail,
    data_product_retire,
    data_products,
    data_share_detail,
    data_share_transition,
    data_shares,
    governance_policies,
    governance_policy_detail,
    governance_policy_transition,
    glossary_term_approve,
    glossary_term_deprecate,
    glossary_term_detail,
    glossary_terms,
    health,
    healthz,
    ingestion_detail,
    ingestions,
    lineage_edges,
    livez,
    metrics,
    master_merge_candidate_approve,
    master_merge_candidates,
    master_record_detail,
    master_records,
    notebook_execution_complete,
    notebook_session_executions,
    notebook_session_terminate,
    notebook_sessions,
    notebook_workspace_sessions,
    notebook_workspaces,
    orchestration_run_transition,
    orchestration_runs,
    orchestration_workflows,
    print_job_detail,
    print_job_status,
    print_jobs,
    project_member_lifecycle,
    project_members,
    project_invitation_accept,
    project_member_invites,
    projects,
    privacy_consent_events,
    privacy_action_decision,
    privacy_action_execute,
    privacy_actions,
    privacy_profile_detail,
    privacy_profiles,
    residency_check,
    residency_profile_activate,
    residency_profile_deprecate,
    residency_profile_detail,
    residency_profiles,
    retention_hold_release,
    retention_holds,
    retention_rules,
    retention_runs,
    quality_results,
    quality_rule_evaluate,
    quality_rules,
    reference_dataset_activate,
    reference_dataset_version_values,
    reference_dataset_versions,
    reference_datasets,
    readyz,
    search_assets,
    stewardship_item_transition,
    stewardship_items,
    user_detail,
    users,
    workflow_definition_detail,
    workflow_definitions,
    workflow_run_tasks,
    workflow_run_transition,
    workflow_runs,
    ui_operations_agent_monitor,
    ui_operations_dashboard,
    ui_operations_orchestration_monitor,
    ui_operations_stewardship_workbench,
)
from tenants.views import tenants

urlpatterns = [
    path('', health, name='health'),
    path('healthz', healthz, name='healthz'),
    path('livez', livez, name='livez'),
    path('readyz', readyz, name='readyz'),
    path('metrics', metrics, name='metrics'),
    path('api/v1/tenants', tenants, name='tenants'),
    path('api/v1/governance/policies', governance_policies, name='governance_policies'),
    path(
        'api/v1/governance/policies/<uuid:policy_id>',
        governance_policy_detail,
        name='governance_policy_detail',
    ),
    path(
        'api/v1/governance/policies/<uuid:policy_id>/transition',
        governance_policy_transition,
        name='governance_policy_transition',
    ),
    path('api/v1/workflows/definitions', workflow_definitions, name='workflow_definitions'),
    path(
        'api/v1/workflows/definitions/<uuid:definition_id>',
        workflow_definition_detail,
        name='workflow_definition_detail',
    ),
    path('api/v1/workflows/runs', workflow_runs, name='workflow_runs'),
    path(
        'api/v1/workflows/runs/<uuid:run_id>/transition',
        workflow_run_transition,
        name='workflow_run_transition',
    ),
    path(
        'api/v1/workflows/runs/<uuid:run_id>/tasks',
        workflow_run_tasks,
        name='workflow_run_tasks',
    ),
    path('api/v1/assets', assets, name='assets'),
    path('api/v1/assets/<uuid:asset_id>', asset_detail, name='asset_detail'),
    path('api/v1/assets/<uuid:asset_id>/classifications', asset_classifications, name='asset_classifications'),
    path('api/v1/assets/<uuid:asset_id>/versions', asset_versions, name='asset_versions'),
    path(
        'api/v1/assets/<uuid:asset_id>/versions/<uuid:version_id>/publish',
        asset_version_publish,
        name='asset_version_publish',
    ),
    path(
        'api/v1/assets/<uuid:asset_id>/terms/<uuid:term_id>',
        asset_glossary_term_link,
        name='asset_glossary_term_link',
    ),
    path('api/v1/glossary/terms', glossary_terms, name='glossary_terms'),
    path('api/v1/glossary/terms/<uuid:term_id>', glossary_term_detail, name='glossary_term_detail'),
    path(
        'api/v1/glossary/terms/<uuid:term_id>/approve',
        glossary_term_approve,
        name='glossary_term_approve',
    ),
    path(
        'api/v1/glossary/terms/<uuid:term_id>/deprecate',
        glossary_term_deprecate,
        name='glossary_term_deprecate',
    ),
    path('api/v1/classifications', classifications, name='classifications'),
    path('api/v1/classifications/<uuid:classification_id>', classification_detail, name='classification_detail'),
    path('api/v1/classifications/<uuid:classification_id>/activate', classification_activate, name='classification_activate'),
    path('api/v1/classifications/<uuid:classification_id>/deprecate', classification_deprecate, name='classification_deprecate'),
    path('api/v1/master-data/<str:entity_type>/records', master_records, name='master_records'),
    path(
        'api/v1/master-data/<str:entity_type>/records/<uuid:master_id>',
        master_record_detail,
        name='master_record_detail',
    ),
    path(
        'api/v1/master-data/<str:entity_type>/merge-candidates',
        master_merge_candidates,
        name='master_merge_candidates',
    ),
    path(
        'api/v1/master-data/<str:entity_type>/merge-candidates/<uuid:candidate_id>/approve',
        master_merge_candidate_approve,
        name='master_merge_candidate_approve',
    ),
    path('api/v1/access-requests', access_requests, name='access_requests'),
    path('api/v1/access-requests/<uuid:request_id>/decision', access_request_decision, name='access_request_decision'),
    path('api/v1/connectors/runs', connector_runs, name='connector_runs'),
    path('api/v1/connectors/runs/<uuid:run_id>/cancel', connector_run_cancel, name='connector_run_cancel'),
    path('api/v1/printing/jobs', print_jobs, name='print_jobs'),
    path('api/v1/printing/jobs/<uuid:job_id>', print_job_detail, name='print_job_detail'),
    path('api/v1/printing/jobs/<uuid:job_id>/status', print_job_status, name='print_job_status'),
    path('api/v1/notebooks/workspaces', notebook_workspaces, name='notebook_workspaces'),
    path(
        'api/v1/notebooks/workspaces/<uuid:workspace_id>/sessions',
        notebook_workspace_sessions,
        name='notebook_workspace_sessions',
    ),
    path('api/v1/notebooks/sessions', notebook_sessions, name='notebook_sessions'),
    path(
        'api/v1/notebooks/sessions/<uuid:session_id>/terminate',
        notebook_session_terminate,
        name='notebook_session_terminate',
    ),
    path(
        'api/v1/notebooks/sessions/<uuid:session_id>/executions',
        notebook_session_executions,
        name='notebook_session_executions',
    ),
    path(
        'api/v1/notebooks/executions/<uuid:execution_id>/complete',
        notebook_execution_complete,
        name='notebook_execution_complete',
    ),
    path('api/v1/collaboration/documents', collaboration_documents, name='collaboration_documents'),
    path(
        'api/v1/collaboration/documents/<uuid:document_id>',
        collaboration_document_detail,
        name='collaboration_document_detail',
    ),
    path(
        'api/v1/collaboration/documents/<uuid:document_id>/session',
        collaboration_document_session,
        name='collaboration_document_session',
    ),
    path(
        'api/v1/collaboration/documents/<uuid:document_id>/versions',
        collaboration_document_versions,
        name='collaboration_document_versions',
    ),
    path('api/v1/assets/<uuid:asset_id>/contracts', asset_contracts, name='asset_contracts'),
    path('api/v1/contracts', contracts, name='contracts'),
    path('api/v1/contracts/<uuid:contract_id>', contract_detail, name='contract_detail'),
    path('api/v1/contracts/<uuid:contract_id>/activate', contract_activate, name='contract_activate'),
    path('api/v1/contracts/<uuid:contract_id>/deprecate', contract_deprecate, name='contract_deprecate'),
    path('api/v1/data-products', data_products, name='data_products'),
    path('api/v1/data-products/<uuid:product_id>', data_product_detail, name='data_product_detail'),
    path(
        'api/v1/data-products/<uuid:product_id>/activate',
        data_product_activate,
        name='data_product_activate',
    ),
    path(
        'api/v1/data-products/<uuid:product_id>/retire',
        data_product_retire,
        name='data_product_retire',
    ),
    path('api/v1/data-shares', data_shares, name='data_shares'),
    path('api/v1/data-shares/<uuid:share_id>', data_share_detail, name='data_share_detail'),
    path(
        'api/v1/data-shares/<uuid:share_id>/transition',
        data_share_transition,
        name='data_share_transition',
    ),
    path('api/v1/retention/rules', retention_rules, name='retention_rules'),
    path('api/v1/retention/holds', retention_holds, name='retention_holds'),
    path('api/v1/retention/holds/<uuid:hold_id>/release', retention_hold_release, name='retention_hold_release'),
    path('api/v1/retention/runs', retention_runs, name='retention_runs'),
    path('api/v1/privacy/profiles', privacy_profiles, name='privacy_profiles'),
    path('api/v1/privacy/profiles/<uuid:profile_id>', privacy_profile_detail, name='privacy_profile_detail'),
    path('api/v1/privacy/consent-events', privacy_consent_events, name='privacy_consent_events'),
    path('api/v1/privacy/actions', privacy_actions, name='privacy_actions'),
    path(
        'api/v1/privacy/actions/<uuid:action_id>/decision',
        privacy_action_decision,
        name='privacy_action_decision',
    ),
    path(
        'api/v1/privacy/actions/<uuid:action_id>/execute',
        privacy_action_execute,
        name='privacy_action_execute',
    ),
    path('api/v1/agent/runs', agent_runs, name='agent_runs'),
    path('api/v1/agent/runs/<uuid:run_id>/transition', agent_run_transition, name='agent_run_transition'),
    path('api/v1/residency/profiles', residency_profiles, name='residency_profiles'),
    path('api/v1/residency/profiles/<uuid:profile_id>', residency_profile_detail, name='residency_profile_detail'),
    path('api/v1/residency/profiles/<uuid:profile_id>/activate', residency_profile_activate, name='residency_profile_activate'),
    path('api/v1/residency/profiles/<uuid:profile_id>/deprecate', residency_profile_deprecate, name='residency_profile_deprecate'),
    path('api/v1/residency/check', residency_check, name='residency_check'),
    path('api/v1/reference-data/datasets', reference_datasets, name='reference_datasets'),
    path('api/v1/reference-data/datasets/<uuid:dataset_id>/versions', reference_dataset_versions, name='reference_dataset_versions'),
    path(
        'api/v1/reference-data/datasets/<uuid:dataset_id>/versions/<int:version>/activate',
        reference_dataset_activate,
        name='reference_dataset_activate',
    ),
    path(
        'api/v1/reference-data/datasets/<uuid:dataset_id>/versions/<int:version>/values',
        reference_dataset_version_values,
        name='reference_dataset_version_values',
    ),
    path('api/v1/quality/rules', quality_rules, name='quality_rules'),
    path('api/v1/quality/rules/<uuid:rule_id>/evaluate', quality_rule_evaluate, name='quality_rule_evaluate'),
    path('api/v1/quality/results', quality_results, name='quality_results'),
    path('api/v1/users', users, name='users'),
    path('api/v1/users/<uuid:user_id>', user_detail, name='user_detail'),
    path('api/v1/projects', projects, name='projects'),
    path(
        'api/v1/projects/<int:project_id>/members',
        project_members,
        name='project_members',
    ),
    path(
        'api/v1/projects/<int:project_id>/members/invite',
        project_member_invites,
        name='project_member_invites',
    ),
    path(
        'api/v1/projects/<int:project_id>/members/<uuid:membership_id>/lifecycle',
        project_member_lifecycle,
        name='project_member_lifecycle',
    ),
    path(
        'api/v1/projects/invitations/accept',
        project_invitation_accept,
        name='project_invitation_accept',
    ),
    path('api/v1/orchestration/workflows', orchestration_workflows, name='orchestration_workflows'),
    path('api/v1/orchestration/runs', orchestration_runs, name='orchestration_runs'),
    path(
        'api/v1/orchestration/runs/<uuid:run_id>/transition',
        orchestration_run_transition,
        name='orchestration_run_transition',
    ),
    path('api/v1/stewardship/items', stewardship_items, name='stewardship_items'),
    path(
        'api/v1/stewardship/items/<uuid:item_id>/transition',
        stewardship_item_transition,
        name='stewardship_item_transition',
    ),
    path('api/v1/ingestions', ingestions, name='ingestions'),
    path('api/v1/ingestions/<uuid:ingestion_id>', ingestion_detail, name='ingestion_detail'),
    path('api/v1/search/assets', search_assets, name='search_assets'),
    path('api/v1/ui/operations/dashboard', ui_operations_dashboard, name='ui_operations_dashboard'),
    path(
        'api/v1/ui/operations/stewardship-workbench',
        ui_operations_stewardship_workbench,
        name='ui_operations_stewardship_workbench',
    ),
    path(
        'api/v1/ui/operations/orchestration-monitor',
        ui_operations_orchestration_monitor,
        name='ui_operations_orchestration_monitor',
    ),
    path(
        'api/v1/ui/operations/agent-monitor',
        ui_operations_agent_monitor,
        name='ui_operations_agent_monitor',
    ),
    path('api/v1/lineage/edges', lineage_edges, name='lineage_edges'),
    path('admin/', admin.site.urls),
]
