apiVersion: v1
kind: Secret
metadata:
  name: mtafiti-backend-secrets
type: Opaque
stringData:
  DJANGO_SECRET_KEY: change-me
  POSTGRES_PASSWORD: change-me
  CELERY_BROKER_URL: amqps://user:password@rabbitmq:5671//
  RABBITMQ_URL: amqps://user:password@rabbitmq:5671//
