{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "mtafiti-platform.fullname" . }}-backend
  labels:
    {{- include "mtafiti-platform.labels" . | nindent 4 }}
spec:
  {{- if .Values.ingress.className }}
  ingressClassName: {{ .Values.ingress.className }}
  {{- end }}
  rules:
    - host: {{ .Values.ingress.controlPlaneHost | quote }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "mtafiti-platform.fullname" . }}-backend
                port:
                  number: {{ .Values.backend.servicePort }}
    - host: {{ .Values.ingress.tenantWildcardHost | quote }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "mtafiti-platform.fullname" . }}-backend
                port:
                  number: {{ .Values.backend.servicePort }}
{{- end }}
