{{- if .Values.migrationJob.enabled }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "mtafiti-platform.fullname" . }}-migrate
  labels:
    {{- include "mtafiti-platform.labels" . | nindent 4 }}
spec:
  backoffLimit: {{ .Values.migrationJob.backoffLimit }}
  template:
    spec:
      restartPolicy: OnFailure
      securityContext:
        {{- toYaml .Values.security.podSecurityContext | nindent 8 }}
      containers:
        - name: migrate
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          securityContext:
            {{- toYaml .Values.security.containerSecurityContext | nindent 12 }}
          command: ["python", "manage.py", "migrate_schemas", "--noinput"]
          env:
            - name: DJANGO_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secrets.name }}
                  key: DJANGO_SECRET_KEY
            - name: POSTGRES_DB
              value: {{ .Values.postgres.database | quote }}
            - name: POSTGRES_USER
              value: {{ .Values.postgres.user | quote }}
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secrets.name }}
                  key: POSTGRES_PASSWORD
            - name: POSTGRES_HOST
              value: {{ .Values.postgres.serviceName | quote }}
            - name: POSTGRES_PORT
              value: {{ .Values.postgres.port | quote }}
{{- end }}
