{{- if .Values.rabbitmq.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.rabbitmq.serviceName }}
  labels:
    {{- include "mtafiti-platform.labels" . | nindent 4 }}
spec:
  selector:
    app.kubernetes.io/component: rabbitmq
    {{- include "mtafiti-platform.selectorLabels" . | nindent 4 }}
  ports:
    - name: amqp
      port: {{ .Values.rabbitmq.port }}
      targetPort: {{ .Values.rabbitmq.port }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "mtafiti-platform.fullname" . }}-rabbitmq
  labels:
    {{- include "mtafiti-platform.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/component: rabbitmq
      {{- include "mtafiti-platform.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        app.kubernetes.io/component: rabbitmq
        {{- include "mtafiti-platform.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: rabbitmq
          image: {{ .Values.rabbitmq.image }}
          ports:
            - containerPort: {{ .Values.rabbitmq.port }}
          readinessProbe:
            tcpSocket:
              port: {{ .Values.rabbitmq.port }}
            initialDelaySeconds: 5
            periodSeconds: 5
          livenessProbe:
            tcpSocket:
              port: {{ .Values.rabbitmq.port }}
            initialDelaySeconds: 10
            periodSeconds: 10
{{- end }}
