# Generated by Django 5.1.14 on 2026-02-24 18:52

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_dataasset'),
    ]

    operations = [
        migrations.CreateModel(
            name='IngestionRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('connector', models.CharField(max_length=100)),
                ('source', models.JSONField(blank=True, default=dict)),
                ('mode', models.CharField(blank=True, max_length=32)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='queued', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
