# Generated by Django 5.1.14 on 2026-02-24 19:08

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_ingestionrequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='LineageEdge',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('edge_type', models.CharField(max_length=100)),
                ('properties', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('from_asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_edges', to='core.dataasset')),
                ('to_asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_edges', to='core.dataasset')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('from_asset', 'to_asset', 'edge_type'), name='uniq_lineage_edge')],
            },
        ),
    ]
