# Generated by Django 5.1.14 on 2026-02-24 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_lineageedge'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataasset',
            name='classifications',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='dataasset',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='dataasset',
            name='owner',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='dataasset',
            name='tags',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
