# Generated by Django 5.1.14 on 2026-02-27 09:09

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_governancepolicy_governancepolicytransition_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlossaryTerm',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('definition', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('approved', 'Approved'), ('deprecated', 'Deprecated')], default='draft', max_length=16)),
                ('owners', models.JSONField(blank=True, default=list)),
                ('stewards', models.JSONField(blank=True, default=list)),
                ('related_asset_ids', models.JSONField(blank=True, default=list)),
                ('classifications', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('name',), name='uniq_glossary_term_name')],
            },
        ),
    ]
