# Generated by Django 5.1.14 on 2026-02-27 14:39

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_dataproduct'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataShare',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('consumer_ref', models.CharField(max_length=256)),
                ('purpose', models.CharField(blank=True, default='', max_length=256)),
                ('constraints', models.JSONField(blank=True, default=dict)),
                ('linked_access_request_ids', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('approved', 'Approved'), ('active', 'Active'), ('revoked', 'Revoked'), ('expired', 'Expired')], default='draft', max_length=16)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.CharField(blank=True, default='', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_shares', to='core.dataasset')),
            ],
        ),
    ]
