# Generated by Django 5.1.14 on 2026-02-27 17:10

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_assetversion'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrivacyAction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action_type', models.CharField(max_length=64)),
                ('status', models.CharField(choices=[('requested', 'Requested'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('executed', 'Executed')], default='requested', max_length=16)),
                ('reason', models.CharField(blank=True, default='', max_length=512)),
                ('actor_id', models.CharField(blank=True, default='', max_length=200)),
                ('evidence', models.JSONField(blank=True, default=dict)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('executed_at', models.DateTimeField(blank=True, null=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='core.privacyprofile')),
            ],
        ),
    ]
