# Generated by Django 5.1.14 on 2026-02-27 03:44

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_workflowdefinition_workflowrun_workflowtask'),
    ]

    operations = [
        migrations.CreateModel(
            name='GovernancePolicy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('version', models.IntegerField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('in_review', 'In Review'), ('approved', 'Approved'), ('active', 'Active'), ('superseded', 'Superseded'), ('rolled_back', 'Rolled Back')], default='draft', max_length=16)),
                ('rules', models.JSONField(blank=True, default=dict)),
                ('reason', models.CharField(blank=True, default='', max_length=512)),
                ('actor_id', models.CharField(blank=True, default='', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rollback_target', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rollback_children', to='core.governancepolicy')),
            ],
        ),
        migrations.CreateModel(
            name='GovernancePolicyTransition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('from_status', models.CharField(max_length=16)),
                ('to_status', models.CharField(max_length=16)),
                ('action', models.CharField(max_length=64)),
                ('reason', models.CharField(blank=True, default='', max_length=512)),
                ('actor_id', models.CharField(blank=True, default='', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transitions', to='core.governancepolicy')),
            ],
        ),
        migrations.AddConstraint(
            model_name='governancepolicy',
            constraint=models.UniqueConstraint(fields=('name', 'version'), name='uniq_governance_policy_name_version'),
        ),
    ]
